version: "3.9"
services:
  backend_hip:
    container_name: testHypothesis_backend_hip
    build:
      context: ./apiHipotesis
      dockerfile: ./dev.Dockerfile
    volumes:
      - ./apiHipotesis:/home/app/backend
  frontend_hip:
    container_name: testHypothesis_frontend_hip
    build:
      context: ./prueba-hipotesis
      dockerfile: ./dev.Dockerfile
    links:
      - backend_hip
    volumes:
      - ./prueba-hipotesis:/home/app/frontend
    depends_on:
      - backend_hip
  nginx_server:
    container_name: testHypotesis_nginx_server
    depends_on:
      - backend_hip
      - frontend_hip
    restart: always
    volumes:
      - ./nginx/devNginx/default.conf:/etc/nginx/conf.d/default.conf:ro
    build:
      context: ./nginx/devNginx
      dockerfile: ./dev.Dockerfile
    ports:
      - "3000:80"
